version: '3'
services:
    bot-int-services:
      container_name: bot-int-services
      build:
        dockerfile: ./Dockerfile
        context: /Users/nxm5777/KSU/capstone-twitter/existing-projects/bot-sense-cont/bot-int-services
      ports:
        - "5000:5000"
      environment:
        - PYTHONUNBUFFERED=0
      networks: 
        - bot-network

    bot-ml:
      container_name: bot-ml
      restart: always
      build:
        dockerfile: ./Dockerfile
        context: /Users/nxm5777/KSU/capstone-twitter/existing-projects/bot-sense-cont/bot-ml
      ports:
        - "5002:5002"
      environment:
        - PYTHONUNBUFFERED=0
      networks: 
        - bot-network

    bot-ui:
      container_name: bot-ui
      restart: always
      build:
        dockerfile: ./Dockerfile
        context: /Users/nxm5777/KSU/capstone-twitter/existing-projects/bot-sense-cont/bot-ui
      ports:
        - "3000:3000"
      networks: 
        - bot-network

networks:
  bot-network:
    driver: bridge